UI
io-oa/GaTe pull request #15
Opened 2024-11-21 13:11 UTC by Edda51

UI added

2024-11-27 14:53 UTC, Edda51 commented
Przybliżyłam trochę grę i powiększyłam HealthBar gracza. Może być?

2024-11-29 16:13 UTC, oskarweb requested changes
Health bar i idle ok, zoom nie ma sensu, bo chcemy mieć większe pole widzenia, możesz ewentualnie zrobić zoom zmieniany na scrollu.

2024-12-02 11:09 UTC, Edda51 commented
OK, usunęłam przybliżenie

2024-12-02 17:13 UTC, oskarweb approved these changes

2024-12-02 17:14 UTC, merged